# Generated by Django 4.1.7 on 2023-12-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectChecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_id_number',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
