# Generated by Django 4.1.7 on 2023-12-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectChecker', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='session',
            field=models.CharField(choices=[('2022/2023', '2022/2023'), ('2021/2022', '2021/2022'), ('2020/2021', '2020/2021'), ('2019/2020', '2019/2020'), ('2018/2019', '2018/2019')], default='2022/2023', max_length=200),
        ),
    ]
